defaults:
  - agent: ppo
  - _self_

env:
  track:
    root: '../f1tenth_racetracks'
    name: 'Austin'
    line_type: 'centerline' # centerline | raceline

  map_path: null
  map_ext: '.png'
  waypoints_path: null

  max_steer: 0.4
  min_steer: -0.4
  max_speed: 5.0
  min_speed: 0.0
  max_lidar_range: 10.0
  obs_dim: 1080
  action_dim: 2

  reward:
    base_reward_scale: 1.0
    progress_coef: 1.0
    speed_coef: 0.02
    collision_penalty: 1.0
    progress_clip: 0.5

eval:
  seed: 42
  checkpoint_dir: null
  episodes: 5
  max_steps: 2000
  num_agents: 1
  video:
    enabled: false
    output_dir: ./records/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
    filename_prefix: rollout
    fps: 20
    size: 900
    margin_m: 20.0

hydra:
  run:
    dir: ./outputs/eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
