/**:
  ros__parameters:
    raceline_csv_path: ""
    direction: "forward"
    map_frame: "map"
    base_frame: "base_link"
    publish_rate_hz: 10.0
    publish_global_path: true
    publish_local_path: true
    publish_local_reference: true
    local_path_length_m: 6.0
    max_local_points: 80
    tf_timeout_sec: 0.05
