/**:
  ros__parameters:
    output_dir: "/record"
    storage_id: mcap
    all_topics: false
    topics:
      - /scan
      - /scan_raw
      - /virtual_scan
      - /camera/left/image_raw
      - /camera/left/camera_info
      - /camera/right/image_raw
      - /camera/right/camera_info
      - /camera/imu
      # - /realsense2_camera/color/camera_info
      # - /realsense2_camera/color/image_raw
      - /jetracer/cmd_drive
      - /jetracer/cmd_drive_target
      - /autonomous/cmd_drive
      - /autonomous/trajectory
      - /autonomous/trajectory_reference
      - /speed_controller/target_speed_mps
      - /speed_controller/measured_speed_mps
      - /speed_controller/speed_error_mps
      - /speed_controller/throttle_cmd
      - /emergency/cmd_drive
      - /emergency/signal
      - /joy
      - /tf
      - /tf_static
      - /robot_description
      - /visual_slam/tracking/slam_path
      - /visual_slam/tracking/odometry
      - /visual_slam/tracking/vo_pose
      - /visual_slam/status
      - /visual_slam/vis/slam_odometry
      - /visual_slam/vis/velocity
      - /localization/current_section
      - /localization/current_section_marker
      - /localization/section_markers
      - /localization_result
      - /initialpose
      - /perception/crop/image
      - /perception/crop/camera_info
      - /perception/crop/roi
