name: "tinylidarnet"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "scan_input"
    data_type: TYPE_FP16
    dims: [ 1, 1081 ]
  }
]
output [
  {
    name: "control_output"
    data_type: TYPE_FP16
    dims: [ 2 ]
  }
]
