/**:
  ros__parameters:
    # フィルター1: ロボット自身の除去
    filter1:
      name: footprint_filter
      type: laser_filters/LaserScanFootprintFilter
      params:
        inscribed_radius: 0.001  # 1 mm

    # フィルター2: メディアンフィルター (平滑化)
    filter2:
      name: median_filter
      type: laser_filters/LaserArrayFilter
      params:
        range_filter_chain:
          filter1:
            name: median_range
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5
        intensity_filter_chain:
          filter1:
            name: median_intensity
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5

    # フィルター3: 飛び点ノイズの除去 (Speckle)
    filter3:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 0             # 隣接点との距離で判断
        max_range: 3.0             # 3m以内の近距離ノイズを対象
        max_range_difference: 0.15 # 15cm以上離れた孤立点をノイズとみなす
        filter_window: 2           # 2つ隣までの点を見る

    # フィルター4: 影のマーキング (Shadows)
    filter4:
      name: shadow_marker
      type: laser_filters/ScanShadowsFilter
      params:
        min_angle: 10.0
        max_angle: 170.0
        neighbors: 10  # 高速走行を考慮し、近傍点は少なめに設定
        window: 1      # 0より1の方が安定することが多い

    filter5:
      name: angle_crop_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.35619   # -135°（rad）
        upper_angle:  2.35619   #  135°（rad）
