<?xml version="1.0"?>
<package format="3">
  <name>system_launch</name>
  <version>0.0.1</version>
  <description>base system launch</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>isaac_ros_dnn_image_encoder</exec_depend>
  <exec_depend>isaac_ros_image_proc</exec_depend>
  <exec_depend>isaac_ros_triton</exec_depend>
  <exec_depend>isaac_ros_scan_image_classifier</exec_depend>
  <exec_depend>scan_image_projection_cropper</exec_depend>
  <exec_depend>speed_controller</exec_depend>
  <exec_depend>drive_mode_manager</exec_depend>
  <exec_depend>hd_map_publisher</exec_depend>
  <exec_depend>hd_map_virtual_scan</exec_depend>
  <exec_depend>vslam_map_tools</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
